### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by eaedk** [CalyGit/Telco-customer-churn#1]
1. Interesting readme, improve with icons, screenshots, present your dataset, etc;
2. Never push your venv;
3. Check the data splitting
```python3
X_train, X_test, y_train, y_test = train_test_split(...)

X_train, X_eval, y_train, y_eval 
#do this instead, so it will be clear that X_test is the provided data that has no y_target included
```
4. No reason to save your models results, just present them in the notebook;
5. Compare models trained with and without smote;
6. I don't see hypothesis testing add it;

Step-by-step guide well followed but ask questions if some aspect are not well understood. Share this review with your teammates.

**Comment by eaedk** [comment]
https://github.com/matiassingers/awesome-readme, have a look then make a more attractive readme.

**Comment by CalyGit** [comment]
> https://github.com/matiassingers/awesome-readme, have a look then make a more attractive readm

> 1. Interesting readme, improve with icons, screenshots, present your dataset, etc;
> 2. Never push your venv;
> 3. Check the data splitting
> 
> ```python
> X_train, X_test, y_train, y_test = train_test_split(...)
> 
> X_train, X_eval, y_train, y_eval 
> #do this instead, so it will be clear that X_test is the provided data that has no y_target included
> ```
> 
> 4. No reason to save your models results, just present them in the notebook;
> 5. Compare models trained with and without smote;
> 6. I don't see hypothesis testing add it;
> 
> Step-by-step guide well followed but ask questions if some aspect are not well understood. Share this review with your teammates.

Thanks for the review Emmanuel. About presenting my datasets, I thought maybe a download link is enough(i.e direct link to download zip file). Maybe you can clarify so that I can make the changes right away.
